services:
  test-postgres:
    image: postgres:latest
    container_name: test-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "55432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  app:
    build: .
    container_name: streamlit-python-validator
    ports:
      - "8501:8501"
    depends_on:
      - test-postgres
    networks:
      - postgres-compose-network

volumes:
  postgres-data:

networks:
  postgres-compose-network:
    driver: bridge
