site_name: Validator Schema Excel
theme:
  name: material
  palette:
    primary: red
  language: pt-br

repo_name: "rafaeljurkfitz/validator-schema-excel"
repo_url: "https://github.com/rafaeljurkfitz/validator-schema-excel"

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python
