name: CI Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: db-pgsql
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.12.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.1

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies with poetry
        run: poetry install

      - name: Run pytest
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: poetry run pytest
